### ISSUE TITLE
Using sublime-phpunit package on macOs with Homestead.

### ISSUE THREAD

**Issue by AshMenhennett** [adamwathan/sublime-phpunit#11]
Problem
=====
I am using Laravel Homestead and all seems well; Terminal runs the correct command, but in relation to the macOS user directory. If the Terminal window in the foreground is ssh'd into the VM, the command is executed as:

    vagrant@homestead:~/code/rounds-smaa$ cd /Users/ashleymenhennett/code/rounds-smaa && phpunit /Users/ashleymenhennett/code/rounds-smaa/tests/RoundsTest.php --filter user_can_see_available_rounds
    -bash: cd: /Users/ashleymenhennett/code/rounds-smaa: No such file or directory

Where I would be requiring the directory, to be something like:

    ~/code/rounds-smaa

to work with the VM (this, would actually work for both situations on UNIX based systems) or maybe even use just the current working directory:

    ./

What I have tried
=====
I had a brief look at ```sublime-phpunit.py``` and altered some code to no avail. 

In particular I have tried changing line 11 of ```sublime-phpunit.py``` to: ```file_name = self.window.active_view().name()``` just to get the name of the file, rather than the full name inc. directory.

Also tried changing calls to ```run_in_terminal``` to the likes of:

    self.run_in_terminal('phpunit ' + file_name)

- removing the ```cd``` call, and ```file_name``` being just the file name, as stated above.

I tried similar changes on all functions that had a call to ```run_in_terminal```.

I was expecting that by altering ```file_name``` (as stated above) and removing calls to ```cd``` (and it's associated arguments- being the directory structure), that this would solve the 'problem'.

I Managed to get the commands being invoked in Terminal to some degree of what I was looking for, but ended up with the commands simply coming out as: 

    phpunit

- no file name or ```--filter``` args (where applicable).

**If it would be of any help, I can go into further detail and more comprehensively list what I have tried. I thought a brief overview would be best to start this Issue off, in regards to time.**

Thoughts
=====
- If I was temporarily to hardcode part of the directory, I would still come up short with the changing project directories on a per project basis:

    ~/code/projectdir

- If I could simply remove the ```cd``` and full path to the test file- ```phpunit /Users/ashleymenhennett/code/rounds-smaa/tests/RoundsTest.php```,  and the working directory in the active Terminal is correct- this should suffice. 

The result would look similar to:

    phpunit filename --filter testname

How would you suggest that I allow for compatibility with a setup such as Homestead?

**Comment by stevejones20** [comment]
I got around this problem by making a change to the sublime-phpunit.py file. I added `.replace('/Users/steve/Sites', '~/Code')` to the end of the `directory`, `file_name` and `php_unit_config_path` lines so it becomes the following:

`def get_paths(self):`
`        file_name = self.window.active_view().file_name()`
`        phpunit_config_path = self.find_phpunit_config(file_name)`
`        directory = os.path.dirname(os.path.realpath(file_name)).replace('/Users/steve/Sites', '~/Code')`
`        file_name = file_name.replace(' ', '\ ').replace('/Users/steve/Sites', '~/Code')`
`        phpunit_config_path = phpunit_config_path.replace(' ', '\ ').replace('/Users/steve/Sites', '~/Code')`
`        active_view = self.window.active_view()`
`        return file_name, phpunit_config_path, active_view, directory`


You would have to alter those paths to match your setup. 

If you then open a terminal window and SSH into Homestead. You can then run the commands using sublime.

**Comment by AshMenhennett** [comment]
Works like a charm!
Thank you!

**Comment by loopold** [comment]
I had exactly the same problem and I found another, simpler solution ('cause I don't know why after changes Sublime stopped to show me PHPUnit at all after cmd+shift+p). Look, just create a symlink:

`vagrant@homestead:~/Code/zasoby$ cd /Users/loop/Code/zasoby && phpunit
-bash: cd: /Users/loop/Code/zasoby: No such file or directory
vagrant@homestead:~/Code/zasoby$ pwd
/home/vagrant/Code/zasoby
vagrant@homestead:~/Code/zasoby$ sudo mkdir /Users
vagrant@homestead:~/Code/zasoby$ sudo ln -s /home/vagrant/ /Users/loop`

It works. Replace /Code/zasoby and your username with yours.

**Comment by tucq88** [comment]
@loopold 's way is very nice. You don't have to change package's file, just need to create symlink to help the `cd` works. 

More details, 
- Open Terminal/Iterm tab that SSH-ed in Homestead, 
- Run the test
- The package will try to `cd` to your project directory, you just need to symlink (map) that directory in to a corresponding one in Homestead (that you shared with Host machine)

E.g, 
I shared `~/Codes` between Hosts and Homesteand, 
I placed code at `/Users/tucq/Codes/my-project`, (which Homestead doesn't understand)

So I have to make a symlink from `/home/vagrant/` to `/Users/tucq`, then the `cd` will work

```
sudo mkdir /Users
sudo ln -s /home/vagrant/ /Users/<your-username>
```
