### ISSUE TITLE
Slow "typing" in iTerm

### ISSUE THREAD

**Issue by lukeberry99** [adamwathan/sublime-phpunit#16]
I'm not sure how best to describe this really, so a gif will have to do. When I press my shortcut to run a test it appears to slowly write in to iTerm instead of pasting it. 

Why does this happen? Any ideas on how to solve this?
![demo](https://cloud.githubusercontent.com/assets/1644147/23558681/66d4d44e-002c-11e7-89cf-9a5751b9491a.gif)

**Comment by lukeberry99** [comment]
I can confirm the same problem occurs in Terminal, and the "typing" effect is slower.

### Edit 1
By disabling zsh and using bash, the problem disappears. Could be an oh-my-zsh plugin I have configured...

### Edit 2 Fixed!

The `oh-my-zsh` plugin called `zsh-autocomplete` is what causes this.

**Comment by drbyte** [comment]
Hmmm ... I don't have the same problem, and I'm using `zsh-autocomplete`.
