### ISSUE TITLE
Console using sublime

### ISSUE THREAD

**Issue by ghost** [adamwathan/sublime-phpunit#20]
Is there a way to get the output, when running a test directly into the console of sublime?

All the best;

**Comment by davidhemphill** [comment]
The Sublime console is just an embedded Python interpreter not a full-blown terminal itself. This package is focused on sending AppleScript commands to dedicated terminal apps. 

Trying to pipe the output from the terminal back to ST's console would be pretty janky, not to mention the terminal already has the output right there in focus. :-)
