### ISSUE TITLE
Running newer version of phpunit with laravel 5.3

### ISSUE THREAD

**Issue by admench** [adamwathan/sublime-phpunit#27]
I'm having problems with my global phpunit version. Laravel 5.3 requires phpunit "phpunit/phpunit": "~5.0", in composer.json but my global version is 6.1.3 - I really want to use your sublime extension, however it runs phpunit globally, not using the local version so my tests just do not run. What is the best approach to overcome this? Of course I can just run ./vendor/bin/phpunit but the sublime extension simply runs phpunit thus tests do not run as expected. Thanks!

A quick solution:
```
alias phpunit="./vendor/bin/phpunit"
```

**Comment by davidhemphill** [comment]
This package is set up to use a project-specific version of phpunit if installed. Are you saying it doesn't run your local version?

**Comment by admench** [comment]
I think I got it working back in May when I posted this.
