### ISSUE TITLE
Windows compatible?

### ISSUE THREAD

**Issue by Luc45** [adamwathan/sublime-phpunit#35]
When I run a test, the console just shows up really fast and disappears.

Is it because I'm running Windows? I think I could fix it by installing fish shell, but I would like to avoid installing third-party software, as my cmd is already colored and all.

Thanks!

**Comment by davidhemphill** [comment]
Yeah, this package relies on AppleScript to do its magic, so I'm afraid it's Mac-only. Sorry!

**Comment by Demers94** [comment]
Sorry for bumping this old closed issue but in case anyone is looking for a good alternative for Windows (it works on OSX/Linux as well), this is a great Sublime plugin : https://github.com/gerardroche/sublime-phpunit

It runs directly in Sublime so you don't even need to switch to your terminal.
