### ISSUE TITLE
iTerm opens, but command not executed (Mojave)

### ISSUE THREAD

**Issue by Robertbaelde** [adamwathan/sublime-phpunit#42]
After upgrading to Mojave the package stopped working with iTerm. When i run a test, it opens iTerm but the phpunit command is not executed. When i try it with the default terminal it works as intended. 

What could be the issue here?

**Comment by devjoca** [comment]
Same issue here :(

**Comment by devjoca** [comment]
@Robertbaelde  I solved this, you have to go to System Preferences -> Security & Privacy -> Privacy -> Accessibility and enable sublime :)

**Comment by Robertbaelde** [comment]
@jopereyral Tnx! I already checked under "Automation", but did not thought about checking "Accessibility". Solved the issue!
