### ISSUE TITLE
How to make it work outside Laravel?

### ISSUE THREAD

**Issue by piercemcgeough** [adamwathan/sublime-phpunit#44]
I was looking to get this setup to work with just a blank setup.

When I run the `run_single_phpunit_test` command from Sublime it creates the following line.
`cd /Users/piercemcgeough/development/php_test && phpunit /Users/piercemcgeough/development/php_test/tests/Feature/SampleTest.php --filter it_is_true`

And get the following error
`Class '/Users/piercemcgeough/development/php_test/tests/Feature/SampleTest' could not be found in '/Users/piercemcgeough/development/php_test/tests/Feature/SampleTest.php'.`

However, if I manually run the following including `./vendor/bin/` It will run as expected
`cd /Users/piercemcgeough/development/php_test && ./vendor/bin/phpunit /Users/piercemcgeough/development/php_test/tests/Feature/SampleTest.php --filter it_is_true`

It appears to be `phpunit` is not transforming to `./vendor/bin/phpunit`

![Screenshot 2019-03-29 at 16 15 02](https://user-images.githubusercontent.com/3092809/55246854-14af6600-523e-11e9-9fa3-b4984c7d9aff.png)

**Comment by adamwathan** [comment]
Should be able to fix it by adding `./vendor/bin` to your PATH.

**Comment by piercemcgeough** [comment]
This is my path here and no luck

`/Users/piercemcgeough/.composer/vendor/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:./vendor/bin`

**Comment by piercemcgeough** [comment]
I had the wrong order. Working now, thanks so much.
