### ISSUE TITLE
Does this package work on linux?

### ISSUE THREAD

**Issue by core77** [adamwathan/sublime-phpunit#46]
When I run the commands the xfce4-terminal opens but nothing happens.

**Comment by ishan-biztech** [comment]
It doesn't work on Linux. See this [comment](https://github.com/adamwathan/sublime-phpunit/issues/43#issuecomment-485441094).

**Comment by davidhemphill** [comment]
This package relies on AppleScript to do its magic and as such is macOS only. Sorry!
